package com.hashmapinc.tempus.witsml.server.api;

import com.hashmapinc.tempus.witsml.server.api.model.WMLS_GetCapResponse;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * Examples code for spring boot with CXF services. HelloPortImpl is the
 * implementation for Hello interface. This class was generated by Apache CXF
 * 3.1.0 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */

@WebService(serviceName = "StoreService", portName = "StoreSoapPort",
        targetNamespace = "http://www.witsml.org/wsdl/120",
        endpointInterface = "com.hashmapinc.tempus.witsml.server.api.IStore")
public class StoreImpl implements IStore {

    private static final Logger LOG = Logger.getLogger(StoreImpl.class.getName());

    @Override
    public String WMLS_GetVersion() {
        LOG.info("Executing GetVersion");
        //TODO: Dynamically set the version from properties set at deploy time.
        return ("1.3.1.1,1.4.1.1");
    }

    @Override
    public WMLS_GetCapResponse WMLS_GetCap(String OptionsIn) {
        LOG.info("Executing GetCap");
        WMLS_GetCapResponse resp = new WMLS_GetCapResponse();
        resp.setResult((short)1);
        resp.setSuppMsgOut("");
        //TODO: Dynamically set the capabilities based off of a properties file that can be set at deploy time.
        resp.setCapabilitiesOut("<capServers xmlns=\"http://www.witsml.org/api/141\" version=\"1.4.1\"><capServer apiVers=\"1.4.1.1\"><function name=\"WMLS_GetFromStore\"><dataObject>well</dataObject></function><function name=\"WMLS_GetBaseMsg\" /><function name=\"WMLS_GetVersion\" /></capServer></capServers>");
        return resp;
    }

    @Override
    public String WMLS_GetBaseMsg(Short ReturnValueIn) {
        LOG.info("Executing GetBaseMsg");
        //TODO: Implement the hash table of error codes that can be appended to at deploy time
        return "This is the return value for: " + ReturnValueIn;
    }
}