//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 10:43:19 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.witsml.org/api/141", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hashmapinc.tempus.witsml.server.api.model.cap.v1411;
